### ISSUE TITLE
 unknown block tag: aplayer 

### ISSUE THREAD

**Issue by jitash** [MoePlayer/hexo-tag-dplayer#8]
Template render error: (unknown path) [Line 12, Column 6]
  unknown block tag: aplayer
    at Object.exports.prettifyError (E:\Blog\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (E:\Blog\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (E:\Blog\node_modules\nunjucks\src\environment.js:327:21)
    at E:\Blog\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (E:\Blog\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (E:\Blog\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (E:\Blog\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (E:\Blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (E:\Blog\node_modules\hexo\lib\hexo\post.js:253:16)
    at E:\Blog\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (E:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\Blog\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (E:\Blog\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (E:\Blog\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (E:\Blog\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (E:\Blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\Blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by dixyes** [comment]
maybe you want [hexo-tag-aplayer](https://github.com/grzhan/hexo-tag-aplayer) for alpayer in hexo？

aplayer is for audio
and dplayer for danmaku

**Comment by jitash** [comment]
{% aplayer "Caffeine" "Jeff Williams" "http://7xq131.com1.z0.glb.clouddn.com/Preparation.mp3" "autoplay" %}	
 
I am so used

**Comment by dixyes** [comment]
make sure that you have hexo-tag-'''a'''player install ed
see https://github.com/grzhan/hexo-tag-aplayer/blob/master/README.md for more detail
